# Generated by Django 3.2.6 on 2021-08-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=120)),
                ('project_type', models.CharField(choices=[('Frontend', 'Forntend'), ('Backend', 'Backend'), ('Database', 'Database'), ('FullStack', 'FullStack')], max_length=40)),
                ('duration', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
