# Generated by Django 3.2.6 on 2021-11-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surface', '0002_workdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='project_type',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('Database', 'Database'), ('FullStack', 'FullStack'), ('Test', 'Test'), ('hello', 'hello')], max_length=40),
        ),
    ]
